org: openmodelproject
app: poll-explorer

service: src
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.7

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: 'arn:aws:s3:::pickles-storage/*'


functions:
  # todo change
  hello:
    handler: handler.hello

    environment:
      BUCKET: pickles-storage
    events:
      - http:
          path: users/create
          method: post
          cors: true


resources:
  Resources:
    PicklesStorage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pickles-storage

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
