POST  https://i8mdraho5k.execute-api.us-east-1.amazonaws.com/prod4/inhousepolls/weight
Content-Type: application/json

{"very likely": 1.0,
  "already voted": 1.0,
  "likely": 0.7,
  "somewhat likely": 0.4,
  "neither likely": 0.2,
  "somewhat unlikely": 0.1,
  "unlikely": 0.05,
  "2020 voted": 0.5,
  "weigh_on_code": "111111111111"
}

###
